DROP TABLE ODONTOLOGOS IF EXISTS;

CREATE TABLE ODONTOLOGOS(
                             ID INT AUTO_INCREMENT PRIMARY KEY,
                             MATRICULA VARCHAR(50) NOT NULL,
                             NOMBRE VARCHAR(50) NOT NULL,
                             APELLIDO VARCHAR(50) NOT NULL

);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT,'AABBCC','PEDRITO', 'PEREZ');